# Maven
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(7eeac48a-bf74-43fc-98f0-d3030d7937ec)'
    appType: 'webApp'
    WebAppName: 'malatestespring'
    deployToSlotOrASE: true
    ResourceGroupName: 'mala-group'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
