# Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: '8'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(7eeac48a-bf74-43fc-98f0-d3030d7937ec)'
    appType: 'webApp'
    WebAppName: 'malatestespring'
    deployToSlotOrASE: true
    ResourceGroupName: 'mala-group'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
